### ISSUE TITLE
watchexec can't run on Paketo Tiny Stack

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/watchexec#22]
This buildpack is currently set up to support the Paketo Tiny Stack in its [buildpack.toml](https://github.com/paketo-buildpacks/watchexec/blob/e18c1c535778e37df69f8c4957c794af70e61c3c/buildpack.toml#L49), but a recent [exploration](https://github.com/paketo-buildpacks/rapid-feedback-loops/blob/91685b5a84498f88d855dbbcbf3a9f97db92c2db/go-tilt-prototype/basic-on-tiny/README.md) into integrating the Paketo Go buildpack with watchexec and Tilt reveals that the watchexec binary itself seems not to run on the Tiny run image due to a missing shared library on which it depends. 

Since the binary this buildpack installs can't run on Tiny, the `buildpack.toml` shouldn't support the stack, in my opinion.

**Comment by dmikusa-pivotal** [comment]
Grrr, this is an annoying bit about Tiny if you are trying to run Rust binaries. Rust binaries compiled in a typical manner against GNU libc & to support stack unwinding need this extra library. If you compile them a bit differently you can get around this and it will run on Tiny.

This should work on Tiny, so I would counter and say that we do one of the following:

1. Compile our own version of watchexec that works on Tiny or possibly use their [MUSL build](https://github.com/watchexec/watchexec/releases/download/cli-v1.17.1/watchexec-1.17.1-x86_64-unknown-linux-musl.tar.xz). That may be sufficient to remove the need for that extra library, but I'd have to test more.

2. Modify Tiny to include the [`libgcc1` package](https://packages.ubuntu.com/bionic-updates/libgcc1) (on Bionic), which amounts to just less than 100k of disk space.

I would personally prefer option #2 because it a.) makes running on Tiny much easier for users of [paketo-community/rust](https://github.com/paketo-community/rust) and b.) opens the door to running a lot more Rust cli tools on Tiny, without the additional work of recompiling.
